### ISSUE TITLE
QGIS macos nightly version package not update anymore

### ISSUE THREAD

**Issue by sshuair** [qgis/QGIS-Mac-Packager#101]
From the nightly version download site: https://qgis.org/downloads/macos/nightly/.

It seems not update for a long time, almost 10 days.

**Comment by PeterPetrik** [comment]
hi restarted the job, let see today

**Comment by sshuair** [comment]
It's not updated. The point release also not came out.

**Comment by jlayt** [comment]
Still no nightlies or PR, and the contents of the https://qgis.org/downloads/macos/ folder looks rather strange:
<img width="604" alt="Screenshot 2020-11-26 at 11 18 19" src="https://user-images.githubusercontent.com/3813093/100344819-55462080-2fd9-11eb-96d4-176b25d8d770.png">

**Comment by sshuair** [comment]
Any progress ?

**Comment by PeterPetrik** [comment]
fixed the packager, should be there tomorrow (I hope)

**Comment by PeterPetrik** [comment]
ok qgis_nightly_master_20201130_100439.dmg is today at download area
