### ISSUE TITLE
3.16.1 not available for download

### ISSUE THREAD

**Issue by e42mercury** [qgis/QGIS-Mac-Packager#103]
The main download link is still for 3.16.0 build (October 27): https://qgis.org/downloads/macos/qgis-macos-pr.dmg
This should be updated with the 3.16.1 version.

**Comment by PeterPetrik** [comment]
fixed the packager, check qgis_pr_final-3_16_1_20201130_063613.dmg on the download area

**Comment by PeterPetrik** [comment]
uploaded now
