### ISSUE TITLE
No output when running from Terminal 

### ISSUE THREAD

**Issue by dkav** [qgis/QGIS-Mac-Packager#104]
Running QGIS 3.16.1 from Terminal, per the README, no longer generates any output. Do I need to add an additional argument?

**Comment by drf5n** [comment]
Rather than trying this in a MacOS Terminal:

    open /Applications/QGIS.app

I found I could get output by entering this instead:

    /Applications/QGIS.app/Contents/MacOS/QGIS


For example:
```

V50883:~ drf$ /Applications/QGIS.app/Contents/MacOS/QGIS 
Warning: QWidget::insertAction: Attempt to insert null action
Warning: QWidget::insertAction: Attempt to insert null action
Warning: QWidget::insertAction: Attempt to insert null action
/Users/drf
Warning: Can't open a pseudo teletype
default KB_LAYOUT_DIR:  "/Users/admin/qgis/builds/pr/install/QGIS.app/Contents/MacOS/../Resources/grass/qtermwidget/kb-layouts"
loadAllColorSchemes
Session::run() - program: "/bin/bash"
Session::run() - arguments: ("")
Warning: Unable to set terminal attributes.
started!

```

(However, if you go on to use `Settings/User Profile/New Profile/...` to create a fresh profile, output from the fresh instance does not report itself to this Terminal. )

**Comment by gioman** [comment]
> Running QGIS 3.16.1 from Terminal, per the README, no longer generates any output. Do I need to add an additional argument?

@dkav for questions now we have https://github.com/qgis/QGIS/discussions

**Comment by dkav** [comment]
@gioman I guess I could have been more explicit. I was indirectly flagging the fact that the instruction in the [README](https://github.com/qgis/QGIS-Mac-Packager/blob/master/README.md#how-to-report-issues) is not compatible with the 3.16.1 release. (Feel free to change the issue title.)
