### ISSUE TITLE
Include missing fonts in build

### ISSUE THREAD

**Issue by dkav** [qgis/QGIS-Mac-Packager#105]
QGIS uses the font families "FreeSans" and "Ubuntu" but these are not included in MacOS. 

From the terminal the following errors are reported:

`Warning: Populating font family aliases took 523 ms. Replace uses of missing font family "FreeSans" with one that exists to avoid this cost. `

`Warning: Populating font family aliases took 438 ms. Replace uses of missing font family "Ubuntu" with one that exists to avoid this cost. `

**Comment by dkav** [comment]
@drf5n notes in this [comment](https://github.com/qgis/QGIS/issues/38961#issuecomment-742103737) that URW Bookman L, and Monotype are also missing.

**Comment by PeterPetrik** [comment]
It is in `src//ui/qgserrordialogbase.ui:52:&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:'Ubuntu'` and  `src//gui/editorwidgets/qgsdatetimeeditconfig.cpp:145:    + QStringLiteral( "</span><a href=\"http://qt-project.org/doc/qt-5/qlocale.html#system\"><span style=\"font-family:'Arial,FreeSans,sans-serif';`... 

we use all different font-families in the code, .. I am not sure if we should package it, or just fix the code to use some common fonts? @3nids thoughts?

**Comment by drf5n** [comment]
Looking at https://www.w3schools.com/cssref/pr_font_font-family.asp  I'd say drop the specific family-names and use generic-names

https://github.com/qgis/QGIS/search?q=font-family shows a number of examples using just default fonts, as well as a number of random fonts.
