### ISSUE TITLE
3.16.2 not available for download

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Mac-Packager#106]
The main download link is still for 3.16.1 build

qgis-macos-pr.dmg | 30-Nov-2020 15:53
-- | --

ba27ee03f4800478d41ac3235087246d9e7873eb8fce4e4b027eaf4e7fe37f35  /Users/admin/qgis/builds/pr/build/..//qgis_pr_final-3_16_1_20201130_063613.dmg

**Comment by PeterPetrik** [comment]
restarted server build, let see if that helps
