### ISSUE TITLE
unable to import gdal (deprecated)

### ISSUE THREAD

**Issue by PeterPetrik** [qgis/QGIS-Mac-Packager#114]
```
import gdal
Traceback (most recent call last):
  File "/Applications/QGIS-Dev.app/Contents/MacOS/../Resources/python/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/QGIS-Dev.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 798, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gdal'
```

but `import osgeo` works 

(nightly from 12/02/2021: 
QGIS version | 3.17.0-Master | QGIS code revision | 4137287031
)

**Comment by PeterPetrik** [comment]
`import osgeo.gdal` works too

**Comment by PeterPetrik** [comment]
looks like `import gdal` is deprecated and removed from GDAL 3.2.1 version we use, see https://pypi.org/project/GDAL/ section "Usage"

**Comment by PeterPetrik** [comment]
this is problem with the QGIS plugins that use import gdal, they should update to 

```
try:
    from osgeo import gdal
except ImportError:
    import gdal
``` 
as suggested in the docs

**Comment by PeterPetrik** [comment]
created tickets: 
- https://gitlab.com/cartolab/pdaltools/-/issues/3
-

**Comment by PeterPetrik** [comment]
note that this is coming in new OSGeo4W (Windows) too!

**Comment by gioman** [comment]
> note that this is coming in new OSGeo4W (Windows) too!

someone already found that @jonnyforestGIS @PedroVenancio

**Comment by PeterPetrik** [comment]
fixes OS Translator II: https://github.com/lutraconsulting/ostranslator-ii/commit/62d262901675185d43655b41942ed837e7ae37b3
