### ISSUE TITLE
QML from PyQt doesn't seem to work

### ISSUE THREAD

**Issue by 3nids** [qgis/QGIS-Mac-Packager#122]
QML from PyQt doesn't seem to work, but I don't get any error message.
This works on a locally compiled QGIS.

I suspect this is due to QML missing from the Qt archive available at https://qgis.org/downloads/macos/deps/qt-5.14.2.tar.gz

@PeterPetrik do you confirm?

**Comment by PeterPetrik** [comment]
@3nids is this the same with the 5.15 nightlies ?

**Comment by 3nids** [comment]
yes, still the same with https://github.com/qgis/QGIS/commit/6e9cae1541

**Comment by M-Rick** [comment]
It has never worked under macOS. For example, if I use this simple QGIS example available from the drop-down list, nothing happens and the preview remains empty
QGIS 3.22 macOS
![Capture d’écran 2022-02-06 à 14 22 10](https://user-images.githubusercontent.com/2520948/152684106-37f0ec9a-65d9-4808-b5e7-9ff6bf5de7a3.png)

QGIS 3.10 Linux
![Capture d’écran du 2022-02-06 14-57-57](https://user-images.githubusercontent.com/2520948/152684428-3cdbe8ce-6ec9-49eb-8df5-bd8aa4832c0d.png)
