### ISSUE TITLE
Mac version on Downloads is not current release

### ISSUE THREAD

**Issue by DogmaT2** [qgis/QGIS-Mac-Packager#123]
## Description
The current release is 3.18.2 but the highest version for Mac on the download page is 3.18.1

Page URL:
https://qgis.org/en/site/forusers/download.html

**Comment by PeterPetrik** [comment]
due to the server update to macos 10.15 builds were broken. Should be
fixed, https://qgis.org/downloads/macos/pr/qgis_pr_final-3_18_2_20210424_130722.dmg
nightly builds are still not working

**Comment by joaoponceleao** [comment]
Just a heads up.
Both the PR and LTR on the server are being blocked by Apple Gatekeeper.
I had to remove the quarantine flag on them to get them to run.

**Comment by gioman** [comment]
> Just a heads up.

@joaoponceleao we know. Allocating the necessary money to do the necessary work did not really raised much interest among voting member in the recent QGIS grants voting (in fact the QEP#218 "Notarizing QGIS for macOS" was dead last)

https://lists.osgeo.org/pipermail/qgis-psc/2021-April/009348.html

but probably the project will move on even without a grant

https://lists.osgeo.org/pipermail/qgis-psc/2021-April/009349.html

**Comment by joaoponceleao** [comment]
I see. Thanks for the information. I imagined Apple would have at least some sort of free or cost-only reduced fee for open-source apps. Shame on them really.

**Comment by jlayt** [comment]
Just to note that while .dmg's have now been generated (2 in fact for each?) there are no checksum files.

There's also a lot of .log and .png files in the pr and ltr folders from all the failed builds which should probably be deleted.

Thanks!
