### ISSUE TITLE
QGIS 3.16.9 and 3.20.1 for macOS not available for download

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Mac-Packager#136]
See https://github.com/qgis/QGIS/issues/44381, https://github.com/qgis/QGIS/issues/44408 and https://github.com/qgis/QGIS-Website/issues/925

**Comment by PeterPetrik** [comment]
all should be available in tomorrow morning

**Comment by multiquadric** [comment]
Builds appear to be failing through Aug 4 @ 11:15 PDT.
