### ISSUE TITLE
QGIS 3.16.9 and 3.20.1 for macOS still not available for download

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Mac-Packager#137]
See: https://github.com/qgis/QGIS/issues/44526#issuecomment-892873356, https://github.com/qgis/QGIS-Mac-Packager/issues/136#issuecomment-892874291 and https://github.com/qgis/QGIS-Website/issues/926

**Comment by PeterPetrik** [comment]
@agiudiceandrea don't you want to join our slack macOS QGIS group? it is more effective to ping me there. if yes write me on Peter.petrik@lutraconsulting.co.uk and I can add you there

**Comment by PeterPetrik** [comment]
The macOS packages are ready for use:

Point Release (PR) 3.20.1
https://qgis.org/downloads/macos/pr/qgis_pr_final-3_20_1_20210805_162007.dmg

Long Term Release (LTR) 3.16.9
https://qgis.org/downloads/macos/ltr/qgis_ltr_final-3_16_9_20210806_022813.dmg

and Nightly 3.21.0
https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20210805_123338.dmg
