### ISSUE TITLE
GRASS is not working - again

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS-Mac-Packager#14]
Tested with QGIS 3.4.9 and 3.8, CC @gioman

**Comment by saberraz** [comment]
I can't capture the log as it closes it despite the fact I ticked the box to keep it open 🤦

**Comment by AndrewAnnex** [comment]
@saberraz a little past a year, 7.8 grass was released this year https://grass.osgeo.org/news/85/15/GRASS-GIS-7-8-0-released/
