### ISSUE TITLE
Release 3.22.10 and 3.26.2 package builds failed

### ISSUE THREAD

**Issue by jlayt** [qgis/QGIS-Mac-Packager#154]
The package build for release 3.22.10 and 3.26.2 failed, apparently on the final signing step. See https://download.qgis.org/downloads/macos/ltr/qgis_ltr_final-3_22_10_20220815_145618.log and https://download.qgis.org/downloads/macos/pr/qgis_pr_final-3_26_2_20220815_120437.log.

```
Package QGIS to /Users/admin/qgis/builds/ltr/build/..//qgis_ltr_final-3_22_10_20220815_145618.dmg
Loading packager configuration ... OK
config for QGIS 3.22.10
config loaded OK
[34;01mPrint identities[39;49;00m
  1) BE0D9DD7BAD99E1AFE8E616E3D02336B382A205F "Developer ID Application: Open Source Geospatial Foundation (4F7N4UDA22)"
     1 valid identities found
[34;01mSigning the QGIS-LTR.app[39;49;00m
/Users/admin/qgis/builds/ltr/bundle/QGIS-LTR.app: errSecInternalComponent
In subcomponent: /Users/admin/qgis/builds/ltr/bundle/QGIS-LTR.app/Contents/MacOS/bin/gdal_pansharpen.py
FAIL
```

**Comment by 3nids** [comment]
looking at it!

**Comment by DelazJ** [comment]
@3nids did you get any progress on this, please? See https://github.com/qgis/QGIS-Website/issues/1029

**Comment by 3nids** [comment]
LTR has just been built and released.
PR should be there very soon.

**Comment by dkav** [comment]
@3nids PR still hasn't been updated.

**Comment by 3nids** [comment]
fixed.
I had to run `security unlock-keychain`
