### ISSUE TITLE
QGIS 3.28 warns that several pdal related dylibs can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by AsgerPetersen** [qgis/QGIS-Mac-Packager#159]
When opening QGIS 3.28 installed with the latest installer as of Nov 30. 2022 these warnings are shown:

![image](https://user-images.githubusercontent.com/1392735/204747044-cd9aa219-1b0a-4b9b-ba41-1d06b3cb7b07.png)
<img width="328" alt="image" src="https://user-images.githubusercontent.com/1392735/204747130-d765cf74-4ae6-4d8c-900c-a17ed4defb60.png">
<img width="328" alt="image" src="https://user-images.githubusercontent.com/1392735/204747203-3dc62a0a-5b6b-453a-8b45-78c5190c1626.png">
<img width="328" alt="image" src="https://user-images.githubusercontent.com/1392735/204747283-03e6447b-612b-4915-bff8-f4e53d41eeb6.png">

**Comment by gioman** [comment]
> When opening QGIS 3.28 installed with the latest installer as of Nov 30. 2022 these warnings are shown:

@AsgerPetersen just tested on a clean install of macOS Montery on a M1 Mac Mini and beside de usual security warning for the QGIS app I didn't get all the warnings you reported.

**Comment by AsgerPetersen** [comment]
@gioman I have an Intel Mac. I asked a colleague test it on his Intel Mac where it installed without any if these warnings.

So it seems this issue is specific to my machine. Sorry for the noise!
