### ISSUE TITLE
Compiling QGIS Server

### ISSUE THREAD

**Issue by news24lor** [qgis/QGIS-Mac-Packager#16]
Thanks for the new release... just one application to drag, great!
But there is one thing missing in this version of QGIS: QGIS Server 3.x

QGIS Server 3.x is compiled within QGIS itself:
Qgis.app/Contents/MacOS/fcgi-bin/qgis_mapserv.fcgi

Once started, the various modules (WMS, WCS, ...) are loaded and the server starts.

The previous version QGIS 2.18.x has the server part compiled inside the application and I use it very much combined with the Apache server in Mac OS X.

Version 3.x of QGIS Server adds some very interesting features including the ability to print without external libraries, better management of the WMS protocol and much more. It would be great to have it inside the application.

Can you include a compiled and working QGIS Server in the next release of QGIS?

Thank you in advance... 
Lorenzo

**Comment by PeterPetrik** [comment]
requires building of https://github.com/Homebrew/homebrew-core/blob/master/Formula/fcgi.rb

**Comment by PeterPetrik** [comment]
part of qgis-deps-0.5.5 and qgis 3.16
