### ISSUE TITLE
Libgrassplugin7 warning on start

### ISSUE THREAD

**Issue by JesusLopTem** [qgis/QGIS-Mac-Packager#18]
Every time I start Qgis I get this error:
`WARNING    Plugin libgrassplugin7 : The plugin will be disabled because it crashed QGIS during last startup. Please report an issue and re-enable the plugin when the problem has been solved.
`
Look at plugins list but can't find libgrassplugin7 and re-enable it.

MacOS 10.13.6 with QGIs 3.8.x

**Comment by cesaregal** [comment]
I have same issue.
MacOS 10.13.6 with QGIS 3.6.

**Comment by CedricLor** [comment]
Same issue here, with MacOS 10.14.3 and QGIS 3.8.3.

**Comment by PeterPetrik** [comment]
fixed in qgis-deps-0.5.4 (nightly2 builds)
