### ISSUE TITLE
Dark mode unreadable

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Mac-Packager#19]
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/178003/62578227-848ec680-b898-11e9-90f6-b103c898793e.png">

Black text on black background is hard to read....

**Comment by PeterPetrik** [comment]
Can you please reopen the issue in the QGIS issue tracker? This repository is for packaging, this is GUI/design issue not related to packaging. Thanks a lot.

**Comment by majdal** [comment]
@PeterPetrik just to make sure, is this issue on the QGIS repo sufficient, or is there another place that we need to report the issue to? https://github.com/qgis/QGIS/issues/28890

**Comment by PeterPetrik** [comment]
that is sufficient, thanks.
