### ISSUE TITLE
Support for Oracle DB 

### ISSUE THREAD

**Issue by PeterPetrik** [qgis/QGIS-Mac-Packager#2]
https://github.com/lutraconsulting/qgis-mac-packager/issues/69

**Comment by PeterPetrik** [comment]
also we need qt driver https://doc.qt.io/qt-5/sql-driver.html#qoci-for-the-oracle-call-interface-oci

**Comment by jef-n** [comment]
Not necessarily - our qocispatial is qoci + some additions for spatial data.

**Comment by PeterPetrik** [comment]
@jef-n not sure if I understand your comment... what is qocispatial?

**Comment by jef-n** [comment]
src/providers/oracle/ocispatial

**Comment by PeterPetrik** [comment]
so i compile thiew qocispatial and place it under PlugIns/sqldrivers and Qt picks it and it works?

**Comment by jef-n** [comment]
yes.

**Comment by PeterPetrik** [comment]
great. for Oracle libraries (libclntsh.so), do we ship them as part of Osgeo4w, so I can add them to MacOS bundle?

**Comment by jef-n** [comment]
> great. for Oracle libraries (libclntsh.so), do we ship them as part of Osgeo4w

yes.

**Comment by PeterPetrik** [comment]
https://www.oracle.com/database/technologies/instant-client.html

Oracle client we use is "free" as  they state
