### ISSUE TITLE
Forgotten translation

### ISSUE THREAD

**Issue by Emic37** [qgis/QGIS-Mac-Packager#20]
Hi, 

I'm really happy that an official installation package would be finally available ! For my use, all works perfectly and this official package allows me to save some 10GB free space than using homebrew packages. Amazing ! 

Just I noticed a tiny "issue" : the translation is missing for the "apple" menu as you can see in the screenshot. Is it possible to fix this forgotting ?

![Capture d’écran 2019-08-26 à 16 02 18](https://user-images.githubusercontent.com/2921424/63697488-4ba19c00-c81d-11e9-8754-817ec28cf746.png)

Thanks in advance.

**Comment by PeterPetrik** [comment]
related to #30

**Comment by PeterPetrik** [comment]
is is still the issue ? @Emic37
