### ISSUE TITLE
nightly failed to build + signing issues

### ISSUE THREAD

**Issue by 3nids** [qgis/QGIS-Mac-Packager#21]
![image](https://user-images.githubusercontent.com/127259/65220192-739dbb80-daba-11e9-8722-baaa407bf29c.png)

with nightly only, 3.4 ok, not tested 3.8

**Comment by PeterPetrik** [comment]
@3nids can you try yesterday's build https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20190917_122608.dmg

it looks like today's build failed with some strange random error

**Comment by jef-n** [comment]
> it looks like today's build failed with some strange random error `hdiutil: detach: timeout for DiskArbitration expired`

Which happens once in a while - I already added retries, that seems to help most of the times - but apparently not every time.

**Comment by jef-n** [comment]
@3nids a build just succeeded.

**Comment by 3nids** [comment]
all god with last nightly
