### ISSUE TITLE
Problem running v.clean from grass on QGIS 3.10 processing

### ISSUE THREAD

**Issue by phborba** [qgis/QGIS-Mac-Packager#23]
As I tried to run v.clean from GRASS on QGIS 3.10, the following errors occurred:

Executing </private/var/folders/l4/f54y8nzx6y7cy535v1ymjptc0000gn/T/processing_5b44b7de08884cfeb7bf64696197bcf3/grassdata/grass_batch_job.sh> ...
ERROR 1: dlopen(/Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_MrSID.dylib, 1): Library not loaded: @executable_path/lib/libltidsdk.dylib
Referenced from: /Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_MrSID.dylib
Reason: image not found
ERROR 1: dlopen(/Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_MrSID.dylib, 1): Library not loaded: @executable_path/lib/libltidsdk.dylib
Referenced from: /Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_MrSID.dylib
Reason: image not found
ERROR 1: dlopen(/Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_ECW_JP2ECW.dylib, 1): Library not loaded: @executable_path/lib/libNCSEcw.dylib
Referenced from: /Applications/QGIS3.10.app/Contents/MacOS/lib/gdal_ECW_JP2ECW.dylib
Reason: image not found
ERROR 1: dlopen(/Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_ECW_JP2ECW.dylib, 1): Library not loaded: @executable_path/lib/libNCSEcw.dylib
Referenced from: /Applications/QGIS3.10.app/Contents/MacOS/lib/gdal_ECW_JP2ECW.dylib
Reason: image not found
ERROR 1: dlopen(/Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_MG4Lidar.dylib, 1): Library not loaded: @executable_path/lib/liblti_lidar_dsdk.1.dylib
Referenced from: /Applications/QGIS3.10.app/Contents/MacOS/lib/gdal_MG4Lidar.dylib
Reason: image not found
ERROR 1: dlopen(/Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_MG4Lidar.dylib, 1): Library not loaded: @executable_path/lib/liblti_lidar_dsdk.1.dylib
Referenced from: /Applications/QGIS3.10.app/Contents/MacOS/lib/gdal_MG4Lidar.dylib
Reason: image not found
ERROR: Vector map <output7049981c7562400e9dd7e3cea020c66d> not found
ERROR 1: dlopen(/Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_MrSID.dylib, 1): Library not loaded: @executable_path/lib/libltidsdk.dylib
Referenced from: /Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_MrSID.dylib
Reason: image not found
ERROR 1: dlopen(/Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_MrSID.dylib, 1): Library not loaded: @executable_path/lib/libltidsdk.dylib
Referenced from: /Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_MrSID.dylib
Reason: image not found
ERROR 1: dlopen(/Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_ECW_JP2ECW.dylib, 1): Library not loaded: @executable_path/lib/libNCSEcw.dylib
Referenced from: /Applications/QGIS3.10.app/Contents/MacOS/lib/gdal_ECW_JP2ECW.dylib
Reason: image not found
ERROR 1: dlopen(/Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_ECW_JP2ECW.dylib, 1): Library not loaded: @executable_path/lib/libNCSEcw.dylib
Referenced from: /Applications/QGIS3.10.app/Contents/MacOS/lib/gdal_ECW_JP2ECW.dylib
Reason: image not found
ERROR 1: dlopen(/Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_MG4Lidar.dylib, 1): Library not loaded: @executable_path/lib/liblti_lidar_dsdk.1.dylib
Referenced from: /Applications/QGIS3.10.app/Contents/MacOS/lib/gdal_MG4Lidar.dylib
Reason: image not found
ERROR 1: dlopen(/Applications/QGIS3.10.app/Contents/Resources/gdal/gdalplugins/2.4/gdal_MG4Lidar.dylib, 1): Library not loaded: @executable_path/lib/liblti_lidar_dsdk.1.dylib
Referenced from: /Applications/QGIS3.10.app/Contents/MacOS/lib/gdal_MG4Lidar.dylib
Reason: image not found
ERROR: Vector map <error7049981c7562400e9dd7e3cea020c66d> not found
Execution of </private/var/folders/l4/f54y8nzx6y7cy535v1ymjptc0000gn/T/processing_5b44b7de08884cfeb7bf64696197bcf3/grassdata/grass_batch_job.sh> finished.
Traceback (most recent call last):
File "/Applications/QGIS3.10.app/Contents/Resources/grass7/bin/_grass76", line 2207, in <module>
main()
File "/Applications/QGIS3.10.app/Contents/Resources/grass7/bin/_grass76", line 2155, in main
clean_all()
File "/Applications/QGIS3.10.app/Contents/Resources/grass7/bin/_grass76", line 1789, in clean_all
gsetup.clean_default_db()
File "/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/python/grass/script/setup.py", line 220, in clean_default_db
conn = gdb.db_connection()
File "/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/python/grass/script/db.py", line 108, in db_connection
nuldev = file(os.devnull, 'w')
NameError: name 'file' is not defined
/Applications/QGIS3.10.app/Contents/Resources/grass7/grass76.sh: line 20: /private/var/folders/l4/f54y8nzx6y7cy535v1ymjptc0000gn/T/processing_5b44b7de08884cfeb7bf64696197bcf3/grassdata/temp_location/PERMANENT: is a directory

**Comment by PeterPetrik** [comment]
@phborba can you try with 3.10.1 if it is fixed?

**Comment by phborba** [comment]
Sure! I’ll test it and let you know the outcome

**Comment by phborba** [comment]
I've just tested it and it works! Thanks a lot!
