### ISSUE TITLE
Proj grid files badly placed or missing

### ISSUE THREAD

**Issue by 3nids** [qgis/QGIS-Mac-Packager#27]
When trying to set a transformation, I get this warning

![image](https://user-images.githubusercontent.com/127259/69418540-2688d080-0d1b-11ea-98ea-143da8a9df7a.png)

it's in 3.4
it looks like the search path is badly formed (it repeats twice `proj`)

**Comment by PeterPetrik** [comment]
fixed in qgis-deps-0.5.4
