### ISSUE TITLE
Support Postgres 12

### ISSUE THREAD

**Issue by joaoponceleao** [qgis/QGIS-Mac-Packager#29]
This QGIS is currently using a version of gdal that does not support postgres 12. This creates issues with ogr2ogr and the DB Manager tool in QGIS.

GDAL was updated to support postgres 12 with version 3.0.2, which is currently in the osgeo4mac repo. Updating the dependency should fix the problem.

**Comment by PeterPetrik** [comment]
blocked by https://github.com/qgis/QGIS-Mac-Packager/issues/12

**Comment by PeterPetrik** [comment]
I am working on the new dependencies build system (outside homebrew), new automatic CI for qgis on Mac and new bundler with GDAL3/PROJ6 that will be ready for 3.14 release at least. I hope the new system will land in nightlies this month. I will keep you informed

**Comment by PeterPetrik** [comment]
nightly2 builds are now running with PG 12.2 https://qgis.org/downloads/macos/nightly2/ 
see https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200717_062433.deps
