### ISSUE TITLE
GDAL build pick PostgreSQL from Homebrew

### ISSUE THREAD

**Issue by alazarolop** [qgis/QGIS-Mac-Packager#42]
Good day, 

I tried to build with new deps this morning and I got stopped when trying to build GDAL
```
Found:
S["PG_LIB"]="-L/usr/local/lib -lpq"
S["PQ_LIBS"]="-L/usr/local/lib -lpq"
"jpeg -lgeotiff -ltiff -lpng -L/usr/local/lib -lpq -lzstd -lproj -lz -lpthread -ldl  -lpcre"
Leaving build environment
File config.status contains /usr/local/lib string <-- CMake picked some homebrew libs!
```
Maybe it's related to some previous messages 
```
checking for PostgreSQL... checking for pkg-config... /usr/local/opt/pkg-config/bin/pkg-config
checking pkg-config is at least version 0.21... yes
```
It seems it's picking PostgreSQL linked formulas from Homebrew. When the Homebrew formula is unlinked, the bulding process can go on without any issue.

Thank you

**Comment by PeterPetrik** [comment]
workaround: unlink Homebrew's postgres
