### ISSUE TITLE
missing GDAL drivers 

### ISSUE THREAD

**Issue by PeterPetrik** [qgis/QGIS-Mac-Packager#48]
differences between GDAL in official QGIS 3.10 with homebrew and qgis-deps GDAL are

- [x] IGNFHeightASCIIGrid -raster- (rov): IGN France height correction ASCII Grid
- [x] GPKG -raster,vector- (rw+vs): GeoPackage
- [ ] EPSILON -raster- (rwv): Epsilon wavelets
- [ ] DODS -raster- (ro): DAP 3.x servers
- [x] Rasterlite -raster- (rwvs): Rasterlite
- [x] MBTiles -raster,vector- (rw+v): MBTiles
- [ ] JPEG2000 -raster,vector- (rwv): JPEG-2000 part 1 (ISO/IEC 15444-1), based on Jasper library
- [ ] JP2OpenJPEG -raster,vector- (rwv): JPEG-2000 driver based on OpenJPEG library
- [ ] HDF4 -raster- (ros): Hierarchical Data Format Release 4
- [ ] HDF4Image -raster- (rw+): HDF4 Dataset
- [ ] PCRaster -raster- (rw+): PCRaster Raster File
- [ ] GIF -raster- (rwv): Graphics Interchange Format (.gif)
- [ ] BIGGIF -raster- (rov): Graphics Interchange Format (.gif)
- [ ] geoPDF

**Comment by PeterPetrik** [comment]
few bits fixed by https://github.com/qgis/QGIS-Mac-Packager/commit/c868b2ae97ec1b100d2e10ea8b92926b04f98ad5

**Comment by marsofearth** [comment]
Can I also add geoPDF support missing also here?

**Comment by PeterPetrik** [comment]
also https://github.com/qgis/QGIS-Mac-Packager/issues/63
