### ISSUE TITLE
Nightly2 crashing at startup

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS-Mac-Packager#56]
The latest nightly2 and the previous one are crashing at startup. The startup screen is showing up and then QGIS crashes.
QGIS 3.15 19 July 2020 à 18:38
I attached the log file.
[Crash log.txt](https://github.com/qgis/QGIS-Mac-Packager/files/4949128/Crash.log.txt)

**Comment by PeterPetrik** [comment]
@M-Rick  can you try with 
https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200723_032054.dmg

**Comment by M-Rick** [comment]
> @M-Rick can you try with
> https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200723_032054.dmg

👍 It works. Thank you.
