### ISSUE TITLE
QGIS nightly2 cannot resolve path of embedded XLSX files

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS-Mac-Packager#58]
When opening a projecting containing embedded XLSX layers, QGIS nightly2 won't find the Excel file.

![Capture d’écran 2020-07-28 à 15 58 34](https://user-images.githubusercontent.com/2520948/88679098-63e5ff00-d0ef-11ea-9617-2d9fdea39358.png)

![Capture d’écran 2020-07-28 à 16 01 57](https://user-images.githubusercontent.com/2520948/88679168-752f0b80-d0ef-11ea-8319-7c6820d8aa8a.png)

**Comment by gioman** [comment]
@M-Rick does it work as expected on 3.10 or 3.14?

**Comment by M-Rick** [comment]
> @M-Rick does it work as expected on 3.10 or 3.14?

Yes even with the nightly 3.15
