### ISSUE TITLE
When reordering attributes fields, they will disappear

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS-Mac-Packager#59]
This is a long standing QGIS Mac bug which affects any version of QGIS 3 Mac.

When we want to reorder the fields in the attributes window, they will disappear after being dragged and dropped.

For example, I try to place Actions at the bottom hand of the list, then they will disappear. It will be necessary to close the window and reopen it again.
![Capture d’écran 2020-07-28 à 16 38 26](https://user-images.githubusercontent.com/2520948/88681505-eff92600-d0f1-11ea-8bfd-dc156e8514f7.png)
Actions have disappeared from the list and QGIS selects by default the PictNumb field just before.
![Capture d’écran 2020-07-28 à 16 38 35](https://user-images.githubusercontent.com/2520948/88681538-fab3bb00-d0f1-11ea-859e-83f83ef23eb4.png)
When opening back the window, Actions are back and placed at the end where I wanted them to be.
Now I want to move the Number field between Photo4 and FileName.
![Capture d’écran 2020-07-28 à 16 38 48](https://user-images.githubusercontent.com/2520948/88681764-3484c180-d0f2-11ea-94d9-50cab2143af5.png)
Once again the Number field disappeared and it is Photo4 that is selected.
![Capture d’écran 2020-07-28 à 16 39 04](https://user-images.githubusercontent.com/2520948/88682019-7a418a00-d0f2-11ea-8b8d-e694c0b2608c.png)
But … when opening back the window, the Number field has been placed at the very end!
![Capture d’écran 2020-07-28 à 16 39 12](https://user-images.githubusercontent.com/2520948/88682164-a78e3800-d0f2-11ea-8d80-cbabf31db4c0.png)

**Comment by gioman** [comment]
@M-Rick shouldn't this be filed in the QGIS bug tracker?

**Comment by M-Rick** [comment]
Good question, but since this bug affects only the MacOS version, that's why I posted it there. What do you think? Do you want I open a new thread in the QGIS bug tracker?

**Comment by gioman** [comment]
@M-Rick we have a label for "macOS only" in the QGIS bug tracker.
