### ISSUE TITLE
GeoPDF export from print composer not supported?

### ISSUE THREAD

**Issue by robintw** [qgis/QGIS-Mac-Packager#63]
The latest official QGIS Mac release doesn't seem to support GeoPDF export from the print composer - it says that it needs at least GDAL version 3.

I've also tried the Kyngchaos builds, but the [latest post](https://www.kyngchaos.com/category/software/) there says that read support for PDFs is not yet built into that, and that is required for GeoPDF export.

Are there any plans to get a later version of GDAL with PDF support included in the official QGIS Mac builds?

**Comment by PeterPetrik** [comment]
try https://qgis.org/downloads/macos/nightly2/ , which will be GDAL3 builds after finishing of QGIS 2020 grant for packaging
