### ISSUE TITLE
Authentication Manager not able to get or set password in Keychain

### ISSUE THREAD

**Issue by thayeray** [qgis/QGIS-Mac-Packager#74]
When opening a project with layers handled by the Authentication Manager, it gives the following errors and warning, despite having typed the correct Keychain password. The typed password is known to be correct, because it puts up the same dialog if the password is entered incorrectly.
Authentication configurations that work in other versions of QGIS do not work with nightly2.

2020-08-21T13:32:00     CRITICAL    Authentication Manager : Retrieving password from your Keychain failed: The user name or passphrase you entered is not correct. (OSStatus -25293).
2020-08-21T13:32:07     CRITICAL    Authentication Manager : Storing password in your Keychain failed: The user name or passphrase you entered is not correct. (OSStatus -25293).
2020-08-21T13:32:07     WARNING    Authentication Manager : Master password could not be written to your Keychain

**Comment by PeterPetrik** [comment]
@thayeray can you do a small test for me please? Open the console and try

```
export QCA_PLUGIN_PATH=/Applications/QGIS.app/Contents/PlugIns/
open /Applications/QGIS.app
```

and let me know if that solved the problem ?

**Comment by thayeray** [comment]
This may be a complication of the database I am connecting to. I tried another with a basic setup and it is able to use the authentication manager.
For the more complicated setup, requiring both TLS and a password, that works in build1 LTR:
I did this from a new bash Terminal. The export works:
$ echo $QCA_PLUGIN_PATH

/Applications/QGIS.app/Contents/PlugIns/

The password dialog says that "sslmode value "verify-full" invalid when SSL support is not compiled in", and I get the same errors as previously stated.


    On Monday, August 24, 2020, 01:10:45 AM EDT, Peter Petrik <notifications@github.com> wrote:  
 
 


@thayeray can you do a small test for me please? Open the console and try
export QCA_PLUGIN_PATH=/Applications/QGIS.app/Contents/PlugIns/
open /Applications/QGIS.app

and let me know if that solved the problem ?

**Comment by PeterPetrik** [comment]
https://github.com/KDE/qca/blob/cfea73392b22f24d3f97071176223c104e76d8bd/src/qca_core.cpp#L480

**Comment by PeterPetrik** [comment]
in that case it looks like postgres  is not compiled with ssl support https://stackoverflow.com/a/36201845/2838364

**Comment by PeterPetrik** [comment]
fixed in qgis-deps-0.5.4 (nightly2)

**Comment by Freda72** [comment]
I have the same issue with a fresh installation of QGIS 3.16 
What tis the solution?

**Comment by gioman** [comment]
> What tis the solution?

@Freda72 the bug seems to be still valid https://github.com/qgis/QGIS/issues/40541

**Comment by seancarmody** [comment]
I have the same problem with QGIS 3.34
