### ISSUE TITLE
PostGIS raster provider not present or working

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS-Mac-Packager#8]
Same setup as in #7 

QGIS does not recognise nor load PostGIS rasters

**Comment by PeterPetrik** [comment]
@gubuntu looks like in https://github.com/qgis/QGIS/pull/33685 Alessandro implemented native provider. Maybe this is fixed already? https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20200930_122919.dmg

**Comment by PeterPetrik** [comment]
staled waiting for feedback, closing
