### ISSUE TITLE
layers in .osm format are not loading

### ISSUE THREAD

**Issue by PeterPetrik** [qgis/QGIS-Mac-Packager#84]
works in gdal2 builds

 I have a few projects with OSM layers and they have the red triangle for non mounting layers

**Comment by Spartacus1** [comment]
Thank you Peter :)

**Comment by PeterPetrik** [comment]
do you have some testing data for me that is not working? @Spartacus1

**Comment by PeterPetrik** [comment]
[map.osm.zip](https://github.com/qgis/QGIS-Mac-Packager/files/5259845/map.osm.zip)

I can open data download from https://www.openstreetmap.org/export#map=16/49.8966/16.3186 on all versions locally installed
QGIS 3.10, QGIS 3.14 and also nightly2 https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200922_013400.dmg

@Spartacus1 can you try with this file, or give me file that is not loading?

(note make sure the file is not corrupted, check `tail -n 5 your_file.osm`)

**Comment by PeterPetrik** [comment]
confirmed from originator Renato Henriques that it works, the file was broken
