### ISSUE TITLE
Tiny Identify Results window

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS-Mac-Packager#9]
The window to display the identified results is always displayed resized at a tiny size.
QGIS 3.6.3-Noosa 0c5774c068
![Capture d’écran 2019-06-12 à 20 50 09](https://user-images.githubusercontent.com/2520948/59550685-db99ae80-8f6d-11e9-91e8-b4d198277a09.png)

**Comment by gioman** [comment]
@M-Rick wrong tracker, must be filed here: https://github.com/qgis/QGIS/issues
