### ISSUE TITLE
qgis_process cannot find proj.db

### ISSUE THREAD

**Issue by alazarolop** [qgis/QGIS-Mac-Packager#90]
I'm trying to use the qgis_process inside the latest nightly build. When I try to run any of the options available, I get this message: 
```
$ ./qgis_process list
proj_create_from_database: Cannot find proj.db
Couldn't load Python support library: Cannot load library /Applications/QGIS.app/Contents/MacOS/qgis_process.app/Contents/lib/qgispython: (dlopen(/Applications/QGIS.app/Contents/MacOS/qgis_process.app/Contents/lib/libqgispython.dylib, 10): image not found)
```
The directory "lib" inside "qgis_process.app" doesn't exist, although a symlink of this dylib can be found in the "lib" folder inside "/Applications/QGIS.app/Contents/".

Should symlinks inside this folder be copied inside the "qgis_process.app"?

**Comment by PeterPetrik** [comment]
Fixed this morning, see https://github.com/qgis/QGIS/issues/38447#issuecomment-703437261

**Comment by alazarolop** [comment]
Great! Thanks a lot.
