### ISSUE TITLE
GRASS GIS 7.8.4

### ISSUE THREAD

**Issue by nilason** [qgis/QGIS-Mac-Packager#92]
GRASS GIS 7.8.4 has just been released (https://github.com/OSGeo/grass/releases/tag/7.8.4).

Some changes that affects this project:

`SHLIB_LD` is now set through CC variable in `configure` and `aclocal.m4`:
https://github.com/OSGeo/grass/blob/d8fbd49af4c206da8db73f4d7ad3d25d50e284c7/configure#L1544
https://github.com/OSGeo/grass/blob/d8fbd49af4c206da8db73f4d7ad3d25d50e284c7/aclocal.m4#L513

update needed for:
https://github.com/qgis/QGIS-Mac-Packager/blob/54872e06a43ef61bf6dae8242e121bd5cec8be11/qgis_deps/recipes/grass/recipe.sh#L38
https://github.com/qgis/QGIS-Mac-Packager/blob/54872e06a43ef61bf6dae8242e121bd5cec8be11/qgis_deps/recipes/grass/recipe.sh#L42

In addition, compiling with `pdal` should now work (https://github.com/OSGeo/grass/pull/479).

Last but not least, grabbing this opportunity to congratulate and thank you for this great work!

**Comment by PeterPetrik** [comment]
Thanks, we can do the update for QGIS 3.18

**Comment by nilason** [comment]
FYI: 7.8.5 has been released (https://github.com/OSGeo/grass/releases/tag/7.8.5). There are no mac-specific changes compared to 7.8.4.

**Comment by PeterPetrik** [comment]
let me try to add it to QGIS 3.18 release
\

**Comment by PeterPetrik** [comment]
Talked with Denis, we will probably not do new qgis-deps package to not break 3.18 after FF, so we can add this to 3.20 if you do not mind?

**Comment by nilason** [comment]
Personally, no problem.
