### ISSUE TITLE
SAGA Simple Filter tool fails.

### ISSUE THREAD

**Issue by mapninja** [qgis/QGIS-Mac-Packager#93]
Looks like MODE & RADIUS Parameters changed to KERNEL_TYPE & KERNEL_RADIUS?

2020-10-20T14:27:08     INFO    SAGA execution commands
             io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_nFuuFL/af684edd72654cfab18dfdad591f2b7a/shasta.sgrd" -FILES "/Users/maples/Downloads/L10/shasta.tif"
             grid_filter "Simple Filter" -INPUT "/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_nFuuFL/af684edd72654cfab18dfdad591f2b7a/shasta.sgrd" -MODE 0 -METHOD 0 -RADIUS 3 -RESULT "/Users/maples/Downloads/L10/ShastaLowpass.sdat"
2020-10-20T14:27:12     INFO    SAGA execution console output
             ____________________________
             
             ##### ## ##### ##
             ### ### ## ###
             ### # ## ## #### # ##
             ### ##### ## # #####
             ##### # ## ##### # ##
             ____________________________
             
             SAGA Version: 7.3.0
             
             ____________________________
             library path: /Applications/QGISNightly.app/Contents/MacOS/lib/saga/
             library name: libio_gdal
             library : io_gdal
             tool : Import Raster
             identifier : 0
             author : O.Conrad (c) 2007 (A.Ringeler)
             ____________________________
             
             
             
             Parameters
             
             
             Grids: No objects
             Files: "/Users/maples/Downloads/L10/shasta.tif"
             Multiple Bands Output: automatic
             Select from Multiple Bands:
             Transformation: true
             Resampling: B-Spline Interpolation
             
             
             loading: /Users/maples/Downloads/L10/shasta.tif
             
             
             
             Driver: GTiff
             
             Bands: 1
             
             Rows: 1416
             
             Columns: 1537
             
             
             loading: shasta
             
             
             Saving grid: /private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_nFuuFL/af684edd72654cfab18dfdad591f2b7a/shasta.sgrd...
             
             
             ____________________________
             
             ##### ## ##### ##
             ### ### ## ###
             ### # ## ## #### # ##
             ### ##### ## # #####
             ##### # ## ##### # ##
             ____________________________
             
             SAGA Version: 7.3.0
             
             Unknown option 'MODE'
             ____________________________
             library path: /Applications/QGISNightly.app/Contents/MacOS/lib/saga/
             library name: libgrid_filter
             library : grid_filter
             tool : Simple Filter
             identifier : 0
             author : O.Conrad (c) 2003
             ____________________________
             
             
             Usage: saga_cmd grid_filter 0 [-INPUT ] [-RESULT ] [-METHOD ] [-KERNEL_TYPE ] [-KERNEL_RADIUS ]
             -INPUT: Grid
             Grid (input)
             -RESULT: Filtered Grid
             Grid (optional output)
             -METHOD: Filter
             Choice
             Available Choices:
             [0] Smooth
             [1] Sharpen
             [2] Edge
             Default: 0
             -KERNEL_TYPE: Kernel Type
             Choice
             Available Choices:
             [0] Square
             [1] Circle
             Default: 1
             -KERNEL_RADIUS: Kernel Radius
             Integer
             Minimum: 1
             Default: 2

**Comment by nyalldawson** [comment]
Not a qgis bug -- try the "saga Nextgen" plugin if you need compatibility with different saga versions

**Comment by mapninja** [comment]
> Not a qgis bug -- try the "saga Nextgen" plugin if you need compatibility with different saga versions

Is there a way to make this plugin work with the SAGA installation in the Nightly build?

**Comment by mapninja** [comment]
I'm also curious about this not being a QGIS bug? Maybe it's a QGIS Mac Packager bug? I mean, SAGA version 7.3 is being packaged with the nightlybuild, right?

**Comment by PeterPetrik** [comment]
QGIS 3.16 on macOS is packaged with PROJ6 library.  To be able to compile SAGA with this version, we have packaged SAGA 7.3.0. Unfortunately, QGIS on other OS have older SAGA versions, notably OSGeo4W contains SAGA 2.3. SAGA notoriously changes the arguments and API to the algorithms (even in patch releases), and therefore it is impossible to maintain the QGIS core SAGA plugin compatible with all versions. To solve this difficult issue, we propose to use SAGA-nextGen plugin (https://plugins.qgis.org/plugins/processing_saga_nextgen)  instead of the core SAGA plugin. For the long term solution, it would be best to remove the SAGA core plugin from QGIS core completely, and leave the saga processing algorithms for the QGIS community plugins.
