### ISSUE TITLE
QGIS 3.10 LTS can't use extensions under MacOS BigSur

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS-Mac-Packager#98]
When running QGIS 3.10 LTS on MacOS BigSur, there is no extension available, there is no access to the official repository and it's even impossible to install from a zip file.

![Capture d’écran 2020-11-14 à 16 16 19](https://user-images.githubusercontent.com/2520948/99150580-eb9f4b80-2695-11eb-9649-266e9638fe5a.png)
![Capture d’écran 2020-11-14 à 16 16 28](https://user-images.githubusercontent.com/2520948/99150584-f0fc9600-2695-11eb-9c38-07a1425ec6aa.png)

Version de QGIS | 3.10.11-A Coruña | Révision du code | d2171173e4
-- | -- | -- | --
Compilé avec Qt | 5.12.3 | Utilisant Qt | 5.12.3
Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compilé avec SQLite | 3.28.0 | Fonctionne avec SQLite | 3.28.0
Version du client PostgreSQL | 11.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.1
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
Version de l'OS | macOS 10.16

**Comment by PeterPetrik** [comment]
@M-Rick is it ok with the point release 3.16?

**Comment by M-Rick** [comment]
> @M-Rick is it ok with the point release 3.16?

Yes no problem. Only the 3.10 version.

**Comment by jlayt** [comment]
Works for me on 3.10.11, 3.12.3, 3.14.16, and 3.16.0 on Big Sur. Tried to check 3.10.12 but the .dmg won't open even though the shasum matches.

**Comment by PeterPetrik** [comment]
I cannot replicate too. This would need probably screensharing and more detailed support. Also 3.16 will become LTR in near future.
