### ISSUE TITLE
Qt Designer in QGIS 3.16 PR won't launch under MacOS BigSur

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS-Mac-Packager#99]
Under MacOS BigSur, Qt Designer crashes at launch in QGIS 3.16.

[Designer crash.log](https://github.com/qgis/QGIS-Mac-Packager/files/5541005/Designer.crash.log)

Version de QGIS | 3.16.0-Hannover | Révision du code | 4af1cbfb97
-- | -- | -- | --
Compilé avec Qt | 5.14.2 | Utilisant Qt | 5.14.2
Compilé avec GDAL/OGR | 3.1.2 | Utilisé avec GDAL/OGR | 3.1.2
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.31.1 | Fonctionne avec SQLite | 3.31.1
Version du client PostgreSQL | 12.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.4
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | macOS 10.16
Extensions Python actives | QuickOSM; processing_js; location_lab; refFunctions; qgis2web; qfieldsync; SgmExpressionFunctions; Mergin; processing; db_manager; MetaSearch

**Comment by PeterPetrik** [comment]
How did you started designer? it **must** be started via script in MacOs/bin/designer, not from the Designer.app

**Comment by M-Rick** [comment]
> How did you started designer? it **must** be started via script in MacOs/bin/designer, not from the Designer.app

Exact! Thank you!

**Comment by M-Rick** [comment]
I created an application to launch it with Platypus.
You just have to drag it into the applications folder.
[Designer.zip](https://github.com/qgis/QGIS-Mac-Packager/files/5542836/Designer.zip)
